[tool.poetry]
name = "ark-db"
version = "0.12.4"
description = "Updates ark-db data"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
license = "GNU General Public License v3.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.23.2"
pandas = "^1.4.4"
Pillow = "^9.2.0"
requests = "^2.28.1"
scipy = "^1.9.1"
beautifulsoup4 = "^4.11.1"
lxml = "^4.9.1"
html5lib = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
