name: Update site data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-msv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"

    - name: Set up Python environment
      run: |
        poetry env use 3.10
        poetry install
    
    - name: Run scripts
      run: |
        poetry run python scripts/farming.py
        poetry run python scripts/perma_shops.py
        poetry run python scripts/event_shops.py
    
    - name: Commit updates
      run: |
        git config --global user.name "astral4"
        git config --global user.email "88992929+astral4@users.noreply.github.com"
        git commit -am "Update site data"
        git push