name: Update material sanity values

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-msv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: "poetry"


    - name: Install requirements
      run: |
        cd scripts
        poetry init
        poetry install
    
    - name: Run script
      run: ./scripts/farming.py
    
    - name: Commit updates
      run: |
        git config --global user.name "Castle-3"
        git config --global user.email "closure@users.noreply.github.com"
        git commit -am "Update material sanity values"
        git push